//! Generated design tokens for the Iced application.
//!
//! Source: `assets/theme/tokens.json`, the single tracked design-token
//! source, generated by `scripts/generate-theme-tokens.py`. Do not edit
//! this file by hand; run `make theme-tokens` after changing the JSON.
//!
//! Values are transcribed from the pinned Iced reference
//! `1e54270a6bb24f15630ece336a0575bdbe5be113` and specified in
//! `docs/flutter-ui-reference-spec.md` §3. `crate::theme` converts these
//! plain values into `iced::Color` and re-exports the public names.

// A token table: some values have no consumer until a later package maps
// one, and an unconsumed token is not dead code.
#![allow(dead_code)]

// ---------------------------------------------------------------------------
// app
// ---------------------------------------------------------------------------

/// `app.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_BACKGROUND: (u8, u8, u8) = (0xF4, 0xF2, 0xED);

/// `app.surface` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SURFACE: (u8, u8, u8) = (0xFF, 0xFE, 0xFB);

/// `app.surfaceMuted` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SURFACE_MUTED: (u8, u8, u8) = (0xEC, 0xE9, 0xE1);

/// `app.text` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_TEXT: (u8, u8, u8) = (0x28, 0x27, 0x24);

/// `app.textMuted` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_TEXT_MUTED: (u8, u8, u8) = (0x72, 0x6F, 0x67);

/// `app.border` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_BORDER: (u8, u8, u8) = (0xD9, 0xD5, 0xCB);

/// `app.accent` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_ACCENT: (u8, u8, u8) = (0x4D, 0x5E, 0x86);

/// `app.accentHovered` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_ACCENT_HOVERED: (u8, u8, u8) = (0x3F, 0x4F, 0x76);

/// `app.accentSoft` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_ACCENT_SOFT: (u8, u8, u8) = (0xE2, 0xE6, 0xF0);

/// `app.success` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SUCCESS: (u8, u8, u8) = (0x4E, 0x75, 0x5D);

/// `app.warning` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_WARNING: (u8, u8, u8) = (0xA7, 0x70, 0x36);

/// `app.danger` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_DANGER: (u8, u8, u8) = (0xA5, 0x43, 0x43);

/// `app.sidebar.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SIDEBAR_BACKGROUND: (u8, u8, u8) = (0xEE, 0xEB, 0xE4);

/// `app.readerControls.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_READER_CONTROLS_BACKGROUND: (u8, u8, u8) = (0xEE, 0xEB, 0xE4);

/// `app.tabStrip.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_TAB_STRIP_BACKGROUND: (u8, u8, u8) = (0xE7, 0xE3, 0xDA);

/// `app.alert.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_ALERT_BACKGROUND: (u8, u8, u8) = (0xF6, 0xE5, 0xE2);

/// `app.panel.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_PANEL_BACKGROUND: (u8, u8, u8) = (0xEE, 0xEB, 0xE4);

/// `app.skeleton.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SKELETON_BACKGROUND: (u8, u8, u8) = (0xE3, 0xDF, 0xD6);

/// `app.skeleton.radius` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SKELETON_RADIUS: f32 = 3.0;

/// `app.bookHover` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_BOOK_HOVER: (u8, u8, u8) = (0xE9, 0xE6, 0xDE);

/// `app.textOnAccent` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_TEXT_ON_ACCENT: (u8, u8, u8) = (0xFF, 0xFF, 0xFF);

/// `app.coverPlaceholder.background` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_COVER_PLACEHOLDER_BACKGROUND: (f32, f32, f32) = (0.3, 0.3, 0.4);

/// `app.shadow.base` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SHADOW_BASE: (u8, u8, u8) = (0x21, 0x20, 0x1E);

/// `app.shadow.cover` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SHADOW_COVER: ((u8, u8, u8), f32) = ((0x21, 0x20, 0x1E), 0.16);

/// `app.shadow.menu` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SHADOW_MENU: ((u8, u8, u8), f32) = ((0x21, 0x20, 0x1E), 0.18);

/// `app.shadow.modal` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SHADOW_MODAL: ((u8, u8, u8), f32) = ((0x21, 0x20, 0x1E), 0.24);

/// `app.shadow.hairline` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_SHADOW_HAIRLINE: ((u8, u8, u8), f32) = ((0x21, 0x20, 0x1E), 0.08);

/// `app.backdrop` — Iced (crates/shosai-app/src/theme.rs, the pinned reference)
pub const APP_BACKDROP: ((u8, u8, u8), f32) = ((0x21, 0x20, 0x1E), 0.42);

/// `app.dark.background` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_BACKGROUND: (u8, u8, u8) = (0x0C, 0x0A, 0x09);

/// `app.dark.foreground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_FOREGROUND: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.card` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_CARD: (u8, u8, u8) = (0x0C, 0x0A, 0x09);

/// `app.dark.cardForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_CARD_FOREGROUND: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.popover` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_POPOVER: (u8, u8, u8) = (0x0C, 0x0A, 0x09);

/// `app.dark.popoverForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_POPOVER_FOREGROUND: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.primary` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_PRIMARY: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.primaryForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_PRIMARY_FOREGROUND: (u8, u8, u8) = (0x1C, 0x19, 0x17);

/// `app.dark.secondary` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_SECONDARY: (u8, u8, u8) = (0x29, 0x25, 0x24);

/// `app.dark.secondaryForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_SECONDARY_FOREGROUND: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.muted` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_MUTED: (u8, u8, u8) = (0x29, 0x25, 0x24);

/// `app.dark.mutedForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_MUTED_FOREGROUND: (u8, u8, u8) = (0xA8, 0xA2, 0x9E);

/// `app.dark.accent` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_ACCENT: (u8, u8, u8) = (0x29, 0x25, 0x24);

/// `app.dark.accentForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_ACCENT_FOREGROUND: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.destructive` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_DESTRUCTIVE: (u8, u8, u8) = (0xEF, 0x44, 0x44);

/// `app.dark.destructiveForeground` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_DESTRUCTIVE_FOREGROUND: (u8, u8, u8) = (0xFA, 0xFA, 0xF9);

/// `app.dark.border` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_BORDER: (u8, u8, u8) = (0x29, 0x25, 0x24);

/// `app.dark.input` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_INPUT: (u8, u8, u8) = (0x29, 0x25, 0x24);

/// `app.dark.ring` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_RING: (u8, u8, u8) = (0xD6, 0xD3, 0xD1);

/// `app.dark.selection` — Retained Flutter: Iced defines no dark application palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this application already rendered with, frozen here so the dark theme is mapped from tokens instead of a package default.
pub const APP_DARK_SELECTION: (u8, u8, u8) = (0x35, 0x51, 0x72);

// ---------------------------------------------------------------------------
// reader
// ---------------------------------------------------------------------------

/// `reader.pageNumberAlpha` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_PAGE_NUMBER_ALPHA: f32 = 0.55;

/// `reader.light.background` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_BACKGROUND: (u8, u8, u8) = (0xFF, 0xFF, 0xFF);

/// `reader.light.text` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_TEXT: (f32, f32, f32) = (0.1, 0.1, 0.1);

/// `reader.light.link` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_LINK: (u8, u8, u8) = (0x17, 0x4E, 0xA6);

/// `reader.light.searchHighlight` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_SEARCH_HIGHLIGHT: ((u8, u8, u8), f32) = ((0xFF, 0xF3, 0xA3), 0.5);

/// `reader.light.searchCurrent` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_SEARCH_CURRENT: ((u8, u8, u8), f32) = ((0xFF, 0xE0, 0x66), 0.45);

/// `reader.light.tableHeaderBackground` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_TABLE_HEADER_BACKGROUND: (u8, u8, u8) = (0xE8, 0xEE, 0xF8);

/// `reader.light.tableHeaderBorder` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_LIGHT_TABLE_HEADER_BORDER: (u8, u8, u8) = (0x59, 0x6B, 0x89);

/// `reader.dark.background` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_BACKGROUND: (f32, f32, f32) = (0.12, 0.12, 0.14);

/// `reader.dark.text` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_TEXT: (f32, f32, f32) = (0.85, 0.85, 0.85);

/// `reader.dark.link` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_LINK: (u8, u8, u8) = (0x8A, 0xB4, 0xF8);

/// `reader.dark.searchHighlight` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_SEARCH_HIGHLIGHT: ((u8, u8, u8), f32) = ((0x4C, 0x3B, 0x00), 0.55);

/// `reader.dark.searchCurrent` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_SEARCH_CURRENT: ((u8, u8, u8), f32) = ((0x5C, 0x45, 0x00), 0.5);

/// `reader.dark.tableHeaderBackground` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_TABLE_HEADER_BACKGROUND: (u8, u8, u8) = (0x2B, 0x34, 0x45);

/// `reader.dark.tableHeaderBorder` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_DARK_TABLE_HEADER_BORDER: (u8, u8, u8) = (0x87, 0x97, 0xB2);

/// `reader.sepia.background` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_BACKGROUND: (f32, f32, f32) = (0.96, 0.92, 0.84);

/// `reader.sepia.text` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_TEXT: (f32, f32, f32) = (0.3, 0.2, 0.1);

/// `reader.sepia.link` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_LINK: (u8, u8, u8) = (0x68, 0x3D, 0x00);

/// `reader.sepia.searchHighlight` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_SEARCH_HIGHLIGHT: ((u8, u8, u8), f32) = ((0xFF, 0xE6, 0x9A), 0.45);

/// `reader.sepia.searchCurrent` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_SEARCH_CURRENT: ((u8, u8, u8), f32) = ((0xF4, 0xCF, 0x64), 0.35);

/// `reader.sepia.tableHeaderBackground` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_TABLE_HEADER_BACKGROUND: (u8, u8, u8) = (0xE5, 0xD6, 0xBA);

/// `reader.sepia.tableHeaderBorder` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_SEPIA_TABLE_HEADER_BORDER: (u8, u8, u8) = (0x6B, 0x54, 0x2E);

/// `reader.selection.dragFill` — Retained Flutter: RFD 6 selection/highlighting has no Iced reference (plan decision 8); the values are the colors this application already painted with.
pub const READER_SELECTION_DRAG_FILL: ((u8, u8, u8), f32) = ((0x90, 0xCA, 0xF9), 0.4);

/// `reader.annotation.green` — Retained Flutter: annotation highlight colors have no Iced reference; the values are the colors this application already painted with.
pub const READER_ANNOTATION_GREEN: ((u8, u8, u8), f32) = ((0x70, 0xB7, 0x7E), 0.4);

/// `reader.annotation.blue` — Retained Flutter: annotation highlight colors have no Iced reference; the values are the colors this application already painted with.
pub const READER_ANNOTATION_BLUE: ((u8, u8, u8), f32) = ((0x6A, 0xA9, 0xE9), 0.4);

/// `reader.annotation.pink` — Retained Flutter: annotation highlight colors have no Iced reference; the values are the colors this application already painted with.
pub const READER_ANNOTATION_PINK: ((u8, u8, u8), f32) = ((0xDC, 0x7C, 0xA5), 0.4);

/// `reader.annotation.purple` — Retained Flutter: annotation highlight colors have no Iced reference; the values are the colors this application already painted with.
pub const READER_ANNOTATION_PURPLE: ((u8, u8, u8), f32) = ((0x88, 0x76, 0xC5), 0.4);

/// `reader.annotation.yellow` — Retained Flutter: annotation highlight colors have no Iced reference; the values are the colors this application already painted with.
pub const READER_ANNOTATION_YELLOW: ((u8, u8, u8), f32) = ((0xE2, 0xBD, 0x54), 0.4);

/// `reader.codeBlock.fallbackBackground` — Iced (crates/shosai-app/src/theme.rs reader palettes)
pub const READER_CODE_BLOCK_FALLBACK_BACKGROUND: (f32, f32, f32) = (0.15, 0.15, 0.18);

// ---------------------------------------------------------------------------
// radius
// ---------------------------------------------------------------------------

/// `radius.small` — Iced (crates/shosai-app/src/theme.rs)
pub const RADIUS_SMALL: f32 = 6.0;

/// `radius.medium` — Iced (crates/shosai-app/src/theme.rs)
pub const RADIUS_MEDIUM: f32 = 10.0;

/// `radius.progress` — Iced (crates/shosai-app/src/theme.rs)
pub const RADIUS_PROGRESS: f32 = 2.0;

// ---------------------------------------------------------------------------
// type
// ---------------------------------------------------------------------------

/// `type.family.ui.latin.iced` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_UI_LATIN_ICED: &str = "Inter Variable";

/// `type.family.ui.latin.flutter` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_UI_LATIN_FLUTTER: &str = "Inter";

/// `type.family.ui.japanese.iced` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_UI_JAPANESE_ICED: &str = "Noto Sans JP";

/// `type.family.ui.japanese.flutter` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_UI_JAPANESE_FLUTTER: &str = "Noto Sans JP";

/// `type.family.editorial.latin.iced` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_EDITORIAL_LATIN_ICED: &str = "Source Serif 4";

/// `type.family.editorial.latin.flutter` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_EDITORIAL_LATIN_FLUTTER: &str = "Source Serif 4";

/// `type.family.editorial.japanese.iced` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_EDITORIAL_JAPANESE_ICED: &str = "Noto Serif JP";

/// `type.family.editorial.japanese.flutter` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_EDITORIAL_JAPANESE_FLUTTER: &str = "Noto Serif JP";

/// `type.family.math.iced` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_MATH_ICED: &str = "Inter Variable";

/// `type.family.math.flutter` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_FAMILY_MATH_FLUTTER: &str = "Inter";

/// `type.size.10` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_10: f32 = 10.0;

/// `type.size.11` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_11: f32 = 11.0;

/// `type.size.12` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_12: f32 = 12.0;

/// `type.size.13` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_13: f32 = 13.0;

/// `type.size.14` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_14: f32 = 14.0;

/// `type.size.16` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_16: f32 = 16.0;

/// `type.size.18` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_18: f32 = 18.0;

/// `type.size.20` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_20: f32 = 20.0;

/// `type.size.24` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_24: f32 = 24.0;

/// `type.size.26` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_26: f32 = 26.0;

/// `type.size.32` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_SIZE_32: f32 = 32.0;

/// `type.reader.titleCompact` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_READER_TITLE_COMPACT: f32 = 15.0;

/// `type.reader.titleWide` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_READER_TITLE_WIDE: f32 = 17.0;

/// `type.reader.edgeGlyphCompact` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_READER_EDGE_GLYPH_COMPACT: f32 = 28.0;

/// `type.reader.edgeGlyphWide` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_READER_EDGE_GLYPH_WIDE: f32 = 36.0;

/// `type.bookmark.empty` — Iced (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
pub const TYPE_BOOKMARK_EMPTY: f32 = 15.0;

// ---------------------------------------------------------------------------
// layout
// ---------------------------------------------------------------------------

/// `layout.reader.compactBreakpoint` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_COMPACT_BREAKPOINT: f32 = 860.0;

/// `layout.reader.spreadMinWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_SPREAD_MIN_WIDTH: f32 = 720.0;

/// `layout.reader.horizontalPadding` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_HORIZONTAL_PADDING: f32 = 112.0;

/// `layout.reader.verticalChrome` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_VERTICAL_CHROME: f32 = 148.0;

/// `layout.reader.searchHeightWide` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_SEARCH_HEIGHT_WIDE: f32 = 52.0;

/// `layout.reader.searchHeightCompact` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_SEARCH_HEIGHT_COMPACT: f32 = 88.0;

/// `layout.reader.moreHeightWide` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_MORE_HEIGHT_WIDE: f32 = 58.0;

/// `layout.reader.moreHeightCompact` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_MORE_HEIGHT_COMPACT: f32 = 84.0;

/// `layout.reader.settingsHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_SETTINGS_HEIGHT: f32 = 62.0;

/// `layout.reader.pageGutter` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_PAGE_GUTTER: f32 = 20.0;

/// `layout.reader.pagePadding` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_PAGE_PADDING: f32 = 20.0;

/// `layout.reader.bookmarksPanelWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_BOOKMARKS_PANEL_WIDTH: f32 = 300.0;

/// `layout.reader.progressWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_READER_PROGRESS_WIDTH: f32 = 280.0;

/// `layout.readerChrome.headerPaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_HEADER_PADDING_VERTICAL: f32 = 8.0;

/// `layout.readerChrome.headerPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_HEADER_PADDING_HORIZONTAL: f32 = 14.0;

/// `layout.readerChrome.headerSpacingCompact` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_HEADER_SPACING_COMPACT: f32 = 6.0;

/// `layout.readerChrome.headerSpacingWide` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_HEADER_SPACING_WIDE: f32 = 14.0;

/// `layout.readerChrome.controlPaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_CONTROL_PADDING_VERTICAL: f32 = 7.0;

/// `layout.readerChrome.controlPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_CONTROL_PADDING_HORIZONTAL: f32 = 10.0;

/// `layout.readerChrome.tabStripPaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_STRIP_PADDING_VERTICAL: f32 = 5.0;

/// `layout.readerChrome.tabStripPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_STRIP_PADDING_HORIZONTAL: f32 = 10.0;

/// `layout.readerChrome.tabStripSpacing` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_STRIP_SPACING: f32 = 3.0;

/// `layout.readerChrome.tabPaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_PADDING_VERTICAL: f32 = 6.0;

/// `layout.readerChrome.tabLabelPaddingLeft` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_LABEL_PADDING_LEFT: f32 = 10.0;

/// `layout.readerChrome.tabLabelPaddingRight` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_LABEL_PADDING_RIGHT: f32 = 4.0;

/// `layout.readerChrome.tabClosePaddingLeft` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_CLOSE_PADDING_LEFT: f32 = 4.0;

/// `layout.readerChrome.tabClosePaddingRight` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_TAB_CLOSE_PADDING_RIGHT: f32 = 8.0;

/// `layout.readerChrome.statusPaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_STATUS_PADDING_VERTICAL: f32 = 7.0;

/// `layout.readerChrome.statusPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_STATUS_PADDING_HORIZONTAL: f32 = 12.0;

/// `layout.readerChrome.statusSpacing` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_STATUS_SPACING: f32 = 5.0;

/// `layout.readerChrome.edgePaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_EDGE_PADDING_VERTICAL: f32 = 12.0;

/// `layout.readerChrome.edgePaddingHorizontalCompact` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_EDGE_PADDING_HORIZONTAL_COMPACT: f32 = 8.0;

/// `layout.readerChrome.edgePaddingHorizontalWide` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_EDGE_PADDING_HORIZONTAL_WIDE: f32 = 16.0;

/// `layout.readerChrome.openingCoverWidth` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_OPENING_COVER_WIDTH: f32 = 140.0;

/// `layout.readerChrome.openingCoverHeight` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_OPENING_COVER_HEIGHT: f32 = 200.0;

/// `layout.readerChrome.openingSpacing` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_OPENING_SPACING: f32 = 14.0;

/// `layout.readerChrome.openingMaxWidth` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_OPENING_MAX_WIDTH: f32 = 320.0;

/// `layout.readerChrome.alertPaddingVertical` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_ALERT_PADDING_VERTICAL: f32 = 7.0;

/// `layout.readerChrome.alertPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_ALERT_PADDING_HORIZONTAL: f32 = 14.0;

/// `layout.readerChrome.alertSpacing` — Iced (crates/shosai-app/src/app.rs reader chrome, the pinned reference)
pub const LAYOUT_READER_CHROME_ALERT_SPACING: f32 = 8.0;

/// `layout.library.compactBreakpoint` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_COMPACT_BREAKPOINT: f32 = 760.0;

/// `layout.library.sidebarWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_SIDEBAR_WIDTH: f32 = 184.0;

/// `layout.library.gridMinColumn` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_GRID_MIN_COLUMN: f32 = 220.0;

/// `layout.library.gridSpacing` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_GRID_SPACING: f32 = 18.0;

/// `layout.library.headerSearchMaxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_HEADER_SEARCH_MAX_WIDTH: f32 = 380.0;

/// `layout.library.pageSize` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_PAGE_SIZE: u32 = 40;

/// `layout.library.searchDebounceMs` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_SEARCH_DEBOUNCE_MS: u32 = 200;

/// `layout.library.collectionPaddingVertical` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_COLLECTION_PADDING_VERTICAL: f32 = 22.0;

/// `layout.library.collectionPaddingHorizontal` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_COLLECTION_PADDING_HORIZONTAL: f32 = 24.0;

/// `layout.library.card.height` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_HEIGHT: f32 = 330.0;

/// `layout.library.card.coverHeight` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_COVER_HEIGHT: f32 = 210.0;

/// `layout.library.card.coverRadius` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_COVER_RADIUS: f32 = 4.0;

/// `layout.library.card.coverShadowOffset` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_COVER_SHADOW_OFFSET: f32 = 4.0;

/// `layout.library.card.coverShadowBlur` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_COVER_SHADOW_BLUR: f32 = 12.0;

/// `layout.library.card.titleHeight` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_TITLE_HEIGHT: f32 = 32.0;

/// `layout.library.card.authorHeight` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_AUTHOR_HEIGHT: f32 = 28.0;

/// `layout.library.card.spacing` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_SPACING: f32 = 4.0;

/// `layout.library.card.metadataGap` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_METADATA_GAP: f32 = 6.0;

/// `layout.library.card.borderWidth` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_BORDER_WIDTH: f32 = 1.0;

/// `layout.library.card.placeholderPadding` — Retained Flutter: the pinned Iced placeholder centres its label with no inset; this inset keeps a long or scaled label's ink inside the placeholder box.
pub const LAYOUT_LIBRARY_CARD_PLACEHOLDER_PADDING: f32 = 8.0;

/// `layout.library.card.menuWidth` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_MENU_WIDTH: f32 = 164.0;

/// `layout.library.card.menuPadding` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_MENU_PADDING: f32 = 4.0;

/// `layout.library.card.menuActionPaddingVertical` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_MENU_ACTION_PADDING_VERTICAL: f32 = 7.0;

/// `layout.library.card.menuActionPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_MENU_ACTION_PADDING_HORIZONTAL: f32 = 10.0;

/// `layout.library.card.menuActionHoverAlpha` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_MENU_ACTION_HOVER_ALPHA: f32 = 0.1;

/// `layout.library.card.triggerPaddingVertical` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_TRIGGER_PADDING_VERTICAL: f32 = 5.0;

/// `layout.library.card.triggerPaddingHorizontal` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_TRIGGER_PADDING_HORIZONTAL: f32 = 8.0;

/// `layout.library.card.triggerOffset` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_TRIGGER_OFFSET: f32 = 8.0;

/// `layout.library.card.triggerScrimAlpha` — Retained Flutter: owner-directed refinement of the pinned card trigger (2026-09-25). Iced paints the trigger as an opaque SURFACE square with a 1 px BORDER (theme.rs book_card_action); the owner asked for a subtler trigger, so the reference's painted geometry keeps its 13 px glyph, [5, 8] padding and radiusSmall but is filled with this translucent ink scrim (app.shadow.base) under a light glyph (app.textOnAccent) instead.
pub const LAYOUT_LIBRARY_CARD_TRIGGER_SCRIM_ALPHA: f32 = 0.5;

/// `layout.library.card.triggerScrimActiveAlpha` — Retained Flutter: the same refinement's hovered, pressed and open-menu weight of the trigger scrim; the reference's own hover only swaps SURFACE for SURFACE_MUTED.
pub const LAYOUT_LIBRARY_CARD_TRIGGER_SCRIM_ACTIVE_ALPHA: f32 = 0.68;

/// `layout.library.card.removePaddingVertical` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_REMOVE_PADDING_VERTICAL: f32 = 3.0;

/// `layout.library.card.removePaddingHorizontal` — Iced (crates/shosai-app/src/app.rs render_book_card and crates/shosai-app/src/widgets.rs book_button, the pinned reference)
pub const LAYOUT_LIBRARY_CARD_REMOVE_PADDING_HORIZONTAL: f32 = 6.0;

/// `layout.library.skeleton.titleBarWidth` — Iced (crates/shosai-app/src/app.rs library_refresh_placeholder and render_loading_book_card, the pinned reference)
pub const LAYOUT_LIBRARY_SKELETON_TITLE_BAR_WIDTH: f32 = 126.0;

/// `layout.library.skeleton.titleBarHeight` — Iced (crates/shosai-app/src/app.rs library_refresh_placeholder and render_loading_book_card, the pinned reference)
pub const LAYOUT_LIBRARY_SKELETON_TITLE_BAR_HEIGHT: f32 = 12.0;

/// `layout.library.skeleton.authorBarWidth` — Iced (crates/shosai-app/src/app.rs library_refresh_placeholder and render_loading_book_card, the pinned reference)
pub const LAYOUT_LIBRARY_SKELETON_AUTHOR_BAR_WIDTH: f32 = 82.0;

/// `layout.library.skeleton.authorBarHeight` — Iced (crates/shosai-app/src/app.rs library_refresh_placeholder and render_loading_book_card, the pinned reference)
pub const LAYOUT_LIBRARY_SKELETON_AUTHOR_BAR_HEIGHT: f32 = 9.0;

/// `layout.library.skeleton.spacing` — Iced (crates/shosai-app/src/app.rs library_refresh_placeholder and render_loading_book_card, the pinned reference)
pub const LAYOUT_LIBRARY_SKELETON_SPACING: f32 = 7.0;

/// `layout.library.emptyState.spacing` — Iced (crates/shosai-app/src/app.rs library_collection's empty composition, the pinned reference)
pub const LAYOUT_LIBRARY_EMPTY_STATE_SPACING: f32 = 14.0;

/// `layout.library.alertPaddingVertical` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_ALERT_PADDING_VERTICAL: f32 = 7.0;

/// `layout.library.alertPaddingHorizontal` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_ALERT_PADDING_HORIZONTAL: f32 = 14.0;

/// `layout.library.continueSectionTrailingSpace` — Iced (crates/shosai-app/src/app.rs library_collection's Space between the continue card and the next section, the pinned reference)
pub const LAYOUT_LIBRARY_CONTINUE_SECTION_TRAILING_SPACE: f32 = 4.0;

/// `layout.library.pagingTriggerDistance` — Retained Flutter: the pinned Iced library pages with an explicit previous/next row; the owner asked for automatic next-page loading (2026-09-25), so this is the distance from the scroll end at which the next page is requested. It has no reference value.
pub const LAYOUT_LIBRARY_PAGING_TRIGGER_DISTANCE: f32 = 400.0;

/// `layout.library.sectionSpacing` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_LIBRARY_SECTION_SPACING: f32 = 16.0;

/// `layout.import.modalMaxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_IMPORT_MODAL_MAX_WIDTH: f32 = 680.0;

/// `layout.import.reviewMaxHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_IMPORT_REVIEW_MAX_HEIGHT: f32 = 760.0;

/// `layout.import.reviewGroupRowHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_IMPORT_REVIEW_GROUP_ROW_HEIGHT: f32 = 28.0;

/// `layout.import.reviewBookRowHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_IMPORT_REVIEW_BOOK_ROW_HEIGHT: f32 = 58.0;

/// `layout.import.reviewOverscan` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_IMPORT_REVIEW_OVERSCAN: f32 = 180.0;

/// `layout.import.reviewDefaultViewportHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_IMPORT_REVIEW_DEFAULT_VIEWPORT_HEIGHT: f32 = 420.0;

/// `layout.settings.contentMaxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_SETTINGS_CONTENT_MAX_WIDTH: f32 = 760.0;

/// `layout.settings.paddingVertical` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_SETTINGS_PADDING_VERTICAL: f32 = 24.0;

/// `layout.settings.paddingHorizontal` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_SETTINGS_PADDING_HORIZONTAL: f32 = 28.0;

/// `layout.modal.removeBookMaxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_MODAL_REMOVE_BOOK_MAX_WIDTH: f32 = 440.0;

/// `layout.modal.moveLibraryMaxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_MODAL_MOVE_LIBRARY_MAX_WIDTH: f32 = 520.0;

/// `layout.continueCard.maxWidth` — Iced (crates/shosai-app/src/app.rs render_continue_card, the pinned reference)
pub const LAYOUT_CONTINUE_CARD_MAX_WIDTH: f32 = 620.0;

/// `layout.continueCard.coverWidth` — Iced (crates/shosai-app/src/app.rs render_continue_card, the pinned reference)
pub const LAYOUT_CONTINUE_CARD_COVER_WIDTH: f32 = 72.0;

/// `layout.continueCard.coverHeight` — Iced (crates/shosai-app/src/app.rs render_continue_card, the pinned reference)
pub const LAYOUT_CONTINUE_CARD_COVER_HEIGHT: f32 = 100.0;

/// `layout.continueCard.detailsHeight` — Iced (crates/shosai-app/src/app.rs render_continue_card, the pinned reference)
pub const LAYOUT_CONTINUE_CARD_DETAILS_HEIGHT: f32 = 100.0;

/// `layout.continueCard.detailsSpacing` — Iced (crates/shosai-app/src/app.rs render_continue_card, the pinned reference)
pub const LAYOUT_CONTINUE_CARD_DETAILS_SPACING: f32 = 6.0;

/// `layout.continueCard.rowSpacing` — Iced (crates/shosai-app/src/app.rs render_continue_card, the pinned reference)
pub const LAYOUT_CONTINUE_CARD_ROW_SPACING: f32 = 14.0;

/// `layout.cover.maxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_COVER_MAX_WIDTH: u32 = 440;

/// `layout.cover.maxHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_COVER_MAX_HEIGHT: u32 = 420;

/// `layout.cover.sourceMaxDimension` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_COVER_SOURCE_MAX_DIMENSION: u32 = 8192;

/// `layout.button.primaryPaddingVertical` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_PRIMARY_PADDING_VERTICAL: f32 = 9.0;

/// `layout.button.primaryPaddingHorizontal` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_PRIMARY_PADDING_HORIZONTAL: f32 = 14.0;

/// `layout.button.secondaryPaddingVertical` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_SECONDARY_PADDING_VERTICAL: f32 = 9.0;

/// `layout.button.secondaryPaddingHorizontal` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_SECONDARY_PADDING_HORIZONTAL: f32 = 14.0;

/// `layout.button.navigationPaddingVertical` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_NAVIGATION_PADDING_VERTICAL: f32 = 9.0;

/// `layout.button.navigationPaddingHorizontal` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_NAVIGATION_PADDING_HORIZONTAL: f32 = 12.0;

/// `layout.button.bookPadding` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_BOOK_PADDING: f32 = 8.0;

/// `layout.button.labelSize` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_BUTTON_LABEL_SIZE: f32 = 14.0;

/// `layout.progress.girth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
pub const LAYOUT_PROGRESS_GIRTH: f32 = 4.0;
