// Generated design tokens for the Flutter frontend.
//
// Source: `assets/theme/tokens.json`, the single tracked design-token
// source, generated by `scripts/generate-theme-tokens.py`. Do not edit
// this file by hand; run `make theme-tokens` after changing the JSON.
//
// Values are transcribed from the pinned Iced reference
// `1e54270a6bb24f15630ece336a0575bdbe5be113` and specified in
// `docs/flutter-ui-reference-spec.md` §3.

import 'dart:ui' show Color;

/// The shared design tokens, mapped from the pinned Iced reference.
abstract final class ShosaiTokens {
  // -------------------------------------------------------------------------
  // app
  // -------------------------------------------------------------------------
  /// `app.background` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appBackground = Color(0xFFF4F2ED);

  /// `app.surface` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appSurface = Color(0xFFFFFEFB);

  /// `app.surfaceMuted` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appSurfaceMuted = Color(0xFFECE9E1);

  /// `app.text` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appText = Color(0xFF282724);

  /// `app.textMuted` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appTextMuted = Color(0xFF726F67);

  /// `app.border` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appBorder = Color(0xFFD9D5CB);

  /// `app.accent` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appAccent = Color(0xFF4D5E86);

  /// `app.accentHovered` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appAccentHovered = Color(0xFF3F4F76);

  /// `app.accentSoft` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appAccentSoft = Color(0xFFE2E6F0);

  /// `app.success` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appSuccess = Color(0xFF4E755D);

  /// `app.warning` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appWarning = Color(0xFFA77036);

  /// `app.danger` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appDanger = Color(0xFFA54343);

  /// `app.sidebar.background` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appSidebarBackground = Color(0xFFEEEBE4);

  /// `app.readerControls.background` — Iced (crates/shosai-app/src/theme.rs,
  /// the pinned reference)
  static const appReaderControlsBackground = Color(0xFFEEEBE4);

  /// `app.tabStrip.background` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appTabStripBackground = Color(0xFFE7E3DA);

  /// `app.alert.background` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appAlertBackground = Color(0xFFF6E5E2);

  /// `app.panel.background` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appPanelBackground = Color(0xFFEEEBE4);

  /// `app.skeleton.background` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appSkeletonBackground = Color(0xFFE3DFD6);

  /// `app.skeleton.radius` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appSkeletonRadius = 3.0;

  /// `app.bookHover` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appBookHover = Color(0xFFE9E6DE);

  /// `app.textOnAccent` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appTextOnAccent = Color(0xFFFFFFFF);

  /// `app.coverPlaceholder.background` — Iced
  /// (crates/shosai-app/src/theme.rs, the pinned reference)
  static const appCoverPlaceholderBackground = Color.from(
    alpha: 1.0,
    red: 0.3,
    green: 0.3,
    blue: 0.4,
  );

  /// `app.shadow.base` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appShadowBase = Color(0xFF21201E);

  /// `app.shadow.cover` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appShadowCover = Color.fromRGBO(0x21, 0x20, 0x1E, 0.16);

  /// `app.shadow.menu` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appShadowMenu = Color.fromRGBO(0x21, 0x20, 0x1E, 0.18);

  /// `app.shadow.modal` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appShadowModal = Color.fromRGBO(0x21, 0x20, 0x1E, 0.24);

  /// `app.shadow.hairline` — Iced (crates/shosai-app/src/theme.rs, the
  /// pinned reference)
  static const appShadowHairline = Color.fromRGBO(0x21, 0x20, 0x1E, 0.08);

  /// `app.backdrop` — Iced (crates/shosai-app/src/theme.rs, the pinned
  /// reference)
  static const appBackdrop = Color.fromRGBO(0x21, 0x20, 0x1E, 0.42);

  /// `app.dark.background` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkBackground = Color(0xFF0C0A09);

  /// `app.dark.foreground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkForeground = Color(0xFFFAFAF9);

  /// `app.dark.card` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkCard = Color(0xFF0C0A09);

  /// `app.dark.cardForeground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkCardForeground = Color(0xFFFAFAF9);

  /// `app.dark.popover` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkPopover = Color(0xFF0C0A09);

  /// `app.dark.popoverForeground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkPopoverForeground = Color(0xFFFAFAF9);

  /// `app.dark.primary` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkPrimary = Color(0xFFFAFAF9);

  /// `app.dark.primaryForeground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkPrimaryForeground = Color(0xFF1C1917);

  /// `app.dark.secondary` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkSecondary = Color(0xFF292524);

  /// `app.dark.secondaryForeground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkSecondaryForeground = Color(0xFFFAFAF9);

  /// `app.dark.muted` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkMuted = Color(0xFF292524);

  /// `app.dark.mutedForeground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkMutedForeground = Color(0xFFA8A29E);

  /// `app.dark.accent` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkAccent = Color(0xFF292524);

  /// `app.dark.accentForeground` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkAccentForeground = Color(0xFFFAFAF9);

  /// `app.dark.destructive` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkDestructive = Color(0xFFEF4444);

  /// `app.dark.destructiveForeground` — Retained Flutter: Iced defines no
  /// dark application palette. The values are the shadcn_ui 0.56.3 'stone'
  /// dark scheme this application already rendered with, frozen here so the
  /// dark theme is mapped from tokens instead of a package default.
  static const appDarkDestructiveForeground = Color(0xFFFAFAF9);

  /// `app.dark.border` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkBorder = Color(0xFF292524);

  /// `app.dark.input` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkInput = Color(0xFF292524);

  /// `app.dark.ring` — Retained Flutter: Iced defines no dark application
  /// palette. The values are the shadcn_ui 0.56.3 'stone' dark scheme this
  /// application already rendered with, frozen here so the dark theme is
  /// mapped from tokens instead of a package default.
  static const appDarkRing = Color(0xFFD6D3D1);

  /// `app.dark.selection` — Retained Flutter: Iced defines no dark
  /// application palette. The values are the shadcn_ui 0.56.3 'stone' dark
  /// scheme this application already rendered with, frozen here so the dark
  /// theme is mapped from tokens instead of a package default.
  static const appDarkSelection = Color(0xFF355172);

  // -------------------------------------------------------------------------
  // reader
  // -------------------------------------------------------------------------
  /// `reader.pageNumberAlpha` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerPageNumberAlpha = 0.55;

  /// `reader.light.background` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerLightBackground = Color(0xFFFFFFFF);

  /// `reader.light.text` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerLightText = Color.from(
    alpha: 1.0,
    red: 0.1,
    green: 0.1,
    blue: 0.1,
  );

  /// `reader.light.link` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerLightLink = Color(0xFF174EA6);

  /// `reader.light.searchHighlight` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerLightSearchHighlight = Color.fromRGBO(
    0xFF,
    0xF3,
    0xA3,
    0.5,
  );

  /// `reader.light.searchCurrent` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerLightSearchCurrent = Color.fromRGBO(
    0xFF,
    0xE0,
    0x66,
    0.45,
  );

  /// `reader.light.tableHeaderBackground` — Iced
  /// (crates/shosai-app/src/theme.rs reader palettes)
  static const readerLightTableHeaderBackground = Color(0xFFE8EEF8);

  /// `reader.light.tableHeaderBorder` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerLightTableHeaderBorder = Color(0xFF596B89);

  /// `reader.dark.background` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerDarkBackground = Color.from(
    alpha: 1.0,
    red: 0.12,
    green: 0.12,
    blue: 0.14,
  );

  /// `reader.dark.text` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerDarkText = Color.from(
    alpha: 1.0,
    red: 0.85,
    green: 0.85,
    blue: 0.85,
  );

  /// `reader.dark.link` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerDarkLink = Color(0xFF8AB4F8);

  /// `reader.dark.searchHighlight` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerDarkSearchHighlight = Color.fromRGBO(
    0x4C,
    0x3B,
    0x00,
    0.55,
  );

  /// `reader.dark.searchCurrent` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerDarkSearchCurrent = Color.fromRGBO(0x5C, 0x45, 0x00, 0.5);

  /// `reader.dark.tableHeaderBackground` — Iced
  /// (crates/shosai-app/src/theme.rs reader palettes)
  static const readerDarkTableHeaderBackground = Color(0xFF2B3445);

  /// `reader.dark.tableHeaderBorder` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerDarkTableHeaderBorder = Color(0xFF8797B2);

  /// `reader.sepia.background` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerSepiaBackground = Color.from(
    alpha: 1.0,
    red: 0.96,
    green: 0.92,
    blue: 0.84,
  );

  /// `reader.sepia.text` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerSepiaText = Color.from(
    alpha: 1.0,
    red: 0.3,
    green: 0.2,
    blue: 0.1,
  );

  /// `reader.sepia.link` — Iced (crates/shosai-app/src/theme.rs reader
  /// palettes)
  static const readerSepiaLink = Color(0xFF683D00);

  /// `reader.sepia.searchHighlight` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerSepiaSearchHighlight = Color.fromRGBO(
    0xFF,
    0xE6,
    0x9A,
    0.45,
  );

  /// `reader.sepia.searchCurrent` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerSepiaSearchCurrent = Color.fromRGBO(
    0xF4,
    0xCF,
    0x64,
    0.35,
  );

  /// `reader.sepia.tableHeaderBackground` — Iced
  /// (crates/shosai-app/src/theme.rs reader palettes)
  static const readerSepiaTableHeaderBackground = Color(0xFFE5D6BA);

  /// `reader.sepia.tableHeaderBorder` — Iced (crates/shosai-app/src/theme.rs
  /// reader palettes)
  static const readerSepiaTableHeaderBorder = Color(0xFF6B542E);

  /// `reader.selection.dragFill` — Retained Flutter: RFD 6
  /// selection/highlighting has no Iced reference (plan decision 8); the
  /// values are the colors this application already painted with.
  static const readerSelectionDragFill = Color.fromRGBO(0x90, 0xCA, 0xF9, 0.4);

  /// `reader.annotation.green` — Retained Flutter: annotation highlight
  /// colors have no Iced reference; the values are the colors this
  /// application already painted with.
  static const readerAnnotationGreen = Color.fromRGBO(0x70, 0xB7, 0x7E, 0.4);

  /// `reader.annotation.blue` — Retained Flutter: annotation highlight
  /// colors have no Iced reference; the values are the colors this
  /// application already painted with.
  static const readerAnnotationBlue = Color.fromRGBO(0x6A, 0xA9, 0xE9, 0.4);

  /// `reader.annotation.pink` — Retained Flutter: annotation highlight
  /// colors have no Iced reference; the values are the colors this
  /// application already painted with.
  static const readerAnnotationPink = Color.fromRGBO(0xDC, 0x7C, 0xA5, 0.4);

  /// `reader.annotation.purple` — Retained Flutter: annotation highlight
  /// colors have no Iced reference; the values are the colors this
  /// application already painted with.
  static const readerAnnotationPurple = Color.fromRGBO(0x88, 0x76, 0xC5, 0.4);

  /// `reader.annotation.yellow` — Retained Flutter: annotation highlight
  /// colors have no Iced reference; the values are the colors this
  /// application already painted with.
  static const readerAnnotationYellow = Color.fromRGBO(0xE2, 0xBD, 0x54, 0.4);

  /// `reader.codeBlock.fallbackBackground` — Iced
  /// (crates/shosai-app/src/theme.rs reader palettes)
  static const readerCodeBlockFallbackBackground = Color.from(
    alpha: 1.0,
    red: 0.15,
    green: 0.15,
    blue: 0.18,
  );

  // -------------------------------------------------------------------------
  // radius
  // -------------------------------------------------------------------------
  /// `radius.small` — Iced (crates/shosai-app/src/theme.rs)
  static const radiusSmall = 6.0;

  /// `radius.medium` — Iced (crates/shosai-app/src/theme.rs)
  static const radiusMedium = 10.0;

  /// `radius.progress` — Iced (crates/shosai-app/src/theme.rs)
  static const radiusProgress = 2.0;

  // -------------------------------------------------------------------------
  // type
  // -------------------------------------------------------------------------
  /// `type.family.ui.latin.iced` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.4, docs/typography.md)
  static const typeFamilyUiLatinIced = 'Inter Variable';

  /// `type.family.ui.latin.flutter` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyUiLatinFlutter = 'Inter';

  /// `type.family.ui.japanese.iced` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyUiJapaneseIced = 'Noto Sans JP';

  /// `type.family.ui.japanese.flutter` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyUiJapaneseFlutter = 'Noto Sans JP';

  /// `type.family.editorial.latin.iced` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyEditorialLatinIced = 'Source Serif 4';

  /// `type.family.editorial.latin.flutter` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyEditorialLatinFlutter = 'Source Serif 4';

  /// `type.family.editorial.japanese.iced` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyEditorialJapaneseIced = 'Noto Serif JP';

  /// `type.family.editorial.japanese.flutter` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeFamilyEditorialJapaneseFlutter = 'Noto Serif JP';

  /// `type.family.math.iced` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeFamilyMathIced = 'Inter Variable';

  /// `type.family.math.flutter` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.4, docs/typography.md)
  static const typeFamilyMathFlutter = 'Inter';

  /// `type.size.10` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize10 = 10.0;

  /// `type.size.11` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize11 = 11.0;

  /// `type.size.12` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize12 = 12.0;

  /// `type.size.13` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize13 = 13.0;

  /// `type.size.14` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize14 = 14.0;

  /// `type.size.16` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize16 = 16.0;

  /// `type.size.18` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize18 = 18.0;

  /// `type.size.20` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize20 = 20.0;

  /// `type.size.24` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize24 = 24.0;

  /// `type.size.26` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize26 = 26.0;

  /// `type.size.32` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeSize32 = 32.0;

  /// `type.reader.titleCompact` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.4, docs/typography.md)
  static const typeReaderTitleCompact = 15.0;

  /// `type.reader.titleWide` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeReaderTitleWide = 17.0;

  /// `type.reader.edgeGlyphCompact` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.4, docs/typography.md)
  static const typeReaderEdgeGlyphCompact = 28.0;

  /// `type.reader.edgeGlyphWide` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.4, docs/typography.md)
  static const typeReaderEdgeGlyphWide = 36.0;

  /// `type.bookmark.empty` — Iced (docs/flutter-ui-reference-spec.md 3.4,
  /// docs/typography.md)
  static const typeBookmarkEmpty = 15.0;

  // -------------------------------------------------------------------------
  // layout
  // -------------------------------------------------------------------------
  /// `layout.reader.compactBreakpoint` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderCompactBreakpoint = 860.0;

  /// `layout.reader.spreadMinWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderSpreadMinWidth = 720.0;

  /// `layout.reader.horizontalPadding` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderHorizontalPadding = 112.0;

  /// `layout.reader.verticalChrome` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderVerticalChrome = 148.0;

  /// `layout.reader.searchHeightWide` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderSearchHeightWide = 52.0;

  /// `layout.reader.searchHeightCompact` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderSearchHeightCompact = 88.0;

  /// `layout.reader.moreHeightWide` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderMoreHeightWide = 58.0;

  /// `layout.reader.moreHeightCompact` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderMoreHeightCompact = 84.0;

  /// `layout.reader.settingsHeight` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderSettingsHeight = 62.0;

  /// `layout.reader.pageGutter` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutReaderPageGutter = 20.0;

  /// `layout.reader.pagePadding` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutReaderPagePadding = 20.0;

  /// `layout.reader.bookmarksPanelWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutReaderBookmarksPanelWidth = 300.0;

  /// `layout.reader.progressWidth` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutReaderProgressWidth = 280.0;

  /// `layout.library.compactBreakpoint` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutLibraryCompactBreakpoint = 760.0;

  /// `layout.library.sidebarWidth` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutLibrarySidebarWidth = 184.0;

  /// `layout.library.gridMinColumn` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutLibraryGridMinColumn = 220.0;

  /// `layout.library.gridSpacing` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutLibraryGridSpacing = 18.0;

  /// `layout.library.headerSearchMaxWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutLibraryHeaderSearchMaxWidth = 380.0;

  /// `layout.library.pageSize` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutLibraryPageSize = 40;

  /// `layout.library.searchDebounceMs` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutLibrarySearchDebounceMs = 200;

  /// `layout.library.collectionPaddingVertical` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutLibraryCollectionPaddingVertical = 22.0;

  /// `layout.library.collectionPaddingHorizontal` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutLibraryCollectionPaddingHorizontal = 24.0;

  /// `layout.library.card.height` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardHeight = 330.0;

  /// `layout.library.card.coverHeight` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardCoverHeight = 210.0;

  /// `layout.library.card.coverRadius` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardCoverRadius = 4.0;

  /// `layout.library.card.coverShadowOffset` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardCoverShadowOffset = 4.0;

  /// `layout.library.card.coverShadowBlur` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardCoverShadowBlur = 12.0;

  /// `layout.library.card.titleHeight` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardTitleHeight = 32.0;

  /// `layout.library.card.authorHeight` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardAuthorHeight = 28.0;

  /// `layout.library.card.spacing` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardSpacing = 4.0;

  /// `layout.library.card.metadataGap` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardMetadataGap = 6.0;

  /// `layout.library.card.borderWidth` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardBorderWidth = 1.0;

  /// `layout.library.card.placeholderPadding` — Retained Flutter: the pinned
  /// Iced placeholder centres its label with no inset; this inset keeps a
  /// long or scaled label's ink inside the placeholder box.
  static const layoutLibraryCardPlaceholderPadding = 8.0;

  /// `layout.library.card.menuWidth` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardMenuWidth = 164.0;

  /// `layout.library.card.menuPadding` — Iced (crates/shosai-app/src/app.rs
  /// render_book_card and crates/shosai-app/src/widgets.rs book_button, the
  /// pinned reference)
  static const layoutLibraryCardMenuPadding = 4.0;

  /// `layout.library.card.menuActionPaddingVertical` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardMenuActionPaddingVertical = 7.0;

  /// `layout.library.card.menuActionPaddingHorizontal` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardMenuActionPaddingHorizontal = 10.0;

  /// `layout.library.card.menuActionHoverAlpha` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardMenuActionHoverAlpha = 0.1;

  /// `layout.library.card.triggerPaddingVertical` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardTriggerPaddingVertical = 5.0;

  /// `layout.library.card.triggerPaddingHorizontal` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardTriggerPaddingHorizontal = 8.0;

  /// `layout.library.card.triggerOffset` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardTriggerOffset = 8.0;

  /// `layout.library.card.triggerScrimAlpha` — Retained Flutter:
  /// owner-directed refinement of the pinned card trigger (2026-09-25). Iced
  /// paints the trigger as an opaque SURFACE square with a 1 px BORDER
  /// (theme.rs book_card_action); the owner asked for a subtler trigger, so
  /// the reference's painted geometry keeps its 13 px glyph, [5, 8] padding
  /// and radiusSmall but is filled with this translucent ink scrim
  /// (app.shadow.base) under a light glyph (app.textOnAccent) instead.
  static const layoutLibraryCardTriggerScrimAlpha = 0.5;

  /// `layout.library.card.triggerScrimActiveAlpha` — Retained Flutter: the
  /// same refinement's hovered, pressed and open-menu weight of the trigger
  /// scrim; the reference's own hover only swaps SURFACE for SURFACE_MUTED.
  static const layoutLibraryCardTriggerScrimActiveAlpha = 0.68;

  /// `layout.library.card.removePaddingVertical` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardRemovePaddingVertical = 3.0;

  /// `layout.library.card.removePaddingHorizontal` — Iced
  /// (crates/shosai-app/src/app.rs render_book_card and
  /// crates/shosai-app/src/widgets.rs book_button, the pinned reference)
  static const layoutLibraryCardRemovePaddingHorizontal = 6.0;

  /// `layout.import.modalMaxWidth` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutImportModalMaxWidth = 680.0;

  /// `layout.import.reviewMaxHeight` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutImportReviewMaxHeight = 760.0;

  /// `layout.import.reviewGroupRowHeight` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutImportReviewGroupRowHeight = 28.0;

  /// `layout.import.reviewBookRowHeight` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutImportReviewBookRowHeight = 58.0;

  /// `layout.import.reviewOverscan` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutImportReviewOverscan = 180.0;

  /// `layout.import.reviewDefaultViewportHeight` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutImportReviewDefaultViewportHeight = 420.0;

  /// `layout.settings.contentMaxWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutSettingsContentMaxWidth = 760.0;

  /// `layout.settings.paddingVertical` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutSettingsPaddingVertical = 24.0;

  /// `layout.settings.paddingHorizontal` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutSettingsPaddingHorizontal = 28.0;

  /// `layout.modal.removeBookMaxWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutModalRemoveBookMaxWidth = 440.0;

  /// `layout.modal.moveLibraryMaxWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutModalMoveLibraryMaxWidth = 520.0;

  /// `layout.continueCard.maxWidth` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutContinueCardMaxWidth = 620.0;

  /// `layout.cover.maxWidth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutCoverMaxWidth = 440;

  /// `layout.cover.maxHeight` — Iced (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutCoverMaxHeight = 420;

  /// `layout.cover.sourceMaxDimension` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutCoverSourceMaxDimension = 8192;

  /// `layout.button.primaryPaddingVertical` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutButtonPrimaryPaddingVertical = 9.0;

  /// `layout.button.primaryPaddingHorizontal` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutButtonPrimaryPaddingHorizontal = 14.0;

  /// `layout.button.secondaryPaddingVertical` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutButtonSecondaryPaddingVertical = 9.0;

  /// `layout.button.secondaryPaddingHorizontal` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutButtonSecondaryPaddingHorizontal = 14.0;

  /// `layout.button.navigationPaddingVertical` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutButtonNavigationPaddingVertical = 9.0;

  /// `layout.button.navigationPaddingHorizontal` — Iced
  /// (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutButtonNavigationPaddingHorizontal = 12.0;

  /// `layout.button.bookPadding` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutButtonBookPadding = 8.0;

  /// `layout.button.labelSize` — Iced (docs/flutter-ui-reference-spec.md
  /// 3.5)
  static const layoutButtonLabelSize = 14.0;

  /// `layout.progress.girth` — Iced (docs/flutter-ui-reference-spec.md 3.5)
  static const layoutProgressGirth = 4.0;
}
