// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancellation`, `from_bridge`, `invalid_request`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterBridge>>
abstract class FlutterBridge implements RustOpaqueInterface {
  Future<FlutterAnnotationAssociationOutcome> associateAnnotationVersion({
    required String sourceVersionId,
    required FlutterDocumentHandle target,
    required BigInt cancellationId,
  });

  bool cancel({required BigInt id});

  Future<FlutterAnnotation> createAnnotation({
    required FlutterDocumentHandle document,
    required BigInt unit,
    required BigInt start,
    required BigInt end,
    required double displayScale,
    required FlutterHighlightColor color,
    String? body,
    required BigInt cancellationId,
  });

  BigInt createCancellation();

  static Future<FlutterBridge> default_() =>
      RustLib.instance.api.crateApiFlutterBridgeDefault();

  Future<bool> deleteAnnotation({
    required FlutterDocumentHandle document,
    required String id,
  });

  Future<void> deleteBookmark({required PlatformInt64 id});

  Future<String> exportBookmarks({required PlatformInt64 bookId});

  Future<List<FlutterImportItem>> importDirectory({
    required String pathKey,
    required bool managed,
    required BigInt cancellationId,
  });

  Future<List<FlutterImportItem>> importPaths({
    required List<String> pathKeys,
    required bool managed,
    required BigInt cancellationId,
  });

  Future<FlutterLibraryPage> libraryPage({
    String? query,
    FlutterBookFormat? format,
    required int limit,
    required int offset,
    required BigInt cancellationId,
  });

  Future<FlutterAnnotationAssociationSourcePage>
  listAnnotationAssociationSources({
    required FlutterDocumentHandle target,
    String? cursor,
    required BigInt limit,
    required BigInt cancellationId,
  });

  Future<List<FlutterAnnotation>> listAnnotations({
    required FlutterDocumentHandle document,
    required double scale,
    required BigInt cancellationId,
  });

  Future<List<FlutterBookmark>> listBookmarks({
    required PlatformInt64 bookId,
    required BigInt cancellationId,
  });

  Future<FlutterReaderSettings> loadReaderSettings({
    required BigInt cancellationId,
  });

  Future<FlutterReadingState?> loadReadingState({
    required PlatformInt64 bookId,
    required BigInt cancellationId,
  });

  factory FlutterBridge() => RustLib.instance.api.crateApiFlutterBridgeNew();

  Future<FlutterDocumentSummary> openDocument({
    required FlutterOpenRequest request,
    required BigInt cancellationId,
  });

  Future<FlutterDocumentSummary> openLibraryBook({
    required PlatformInt64 bookId,
    required BigInt cancellationId,
  });

  bool releaseBuffer({required FlutterBufferHandle handle});

  bool releaseCancellation({required BigInt id});

  bool releaseDocument({required FlutterDocumentHandle handle});

  bool releaseSelection({required FlutterSelectionHandle handle});

  Future<bool> removeLibraryBook({required PlatformInt64 bookId});

  Future<FlutterRenderedBuffer> renderPage({
    required FlutterDocumentHandle document,
    required BigInt page,
    required double scale,
    required BigInt cancellationId,
  });

  /// Diagnostic round trip for measuring generated-code DTO transfer and
  /// Dart materialization independently of document layout.
  FlutterSelectionSurface roundTripVisibleScene({
    required FlutterSelectionSurface scene,
  });

  Future<void> saveReaderSettings({required FlutterReaderSettings value});

  Future<void> saveReadingState({
    required PlatformInt64 bookId,
    required FlutterReadingState value,
    required BigInt unitCount,
  });

  Future<List<FlutterSearchMatch>> searchDocument({
    required FlutterDocumentHandle document,
    required String query,
    required BigInt cancellationId,
  });

  Future<FlutterSelectionSurface> selectionSurface({
    required FlutterDocumentHandle document,
    required BigInt unit,
    required double scale,
    required double width,
    required double fontSize,
    required BigInt cancellationId,
  });

  Uint8List takeBuffer({required FlutterBufferHandle handle});

  Future<FlutterBookmark?> toggleBookmark({
    required PlatformInt64 bookId,
    required BigInt unit,
    BigInt? offset,
    String? title,
  });

  Future<bool> updateAnnotation({
    required FlutterDocumentHandle document,
    required String id,
    required FlutterHighlightColor color,
    String? body,
  });

  Future<void> updateBookmark({
    required PlatformInt64 id,
    String? title,
    String? note,
  });

  /// Construct a bridge with a host-provided SQLite database path.
  static FlutterBridge withDatabasePath({required String databasePath}) =>
      RustLib.instance.api.crateApiFlutterBridgeWithDatabasePath(
        databasePath: databasePath,
      );
}

class FlutterAnnotation {
  final String id;
  final BigInt unit;
  final FlutterAnnotationResolution resolution;
  final FlutterAnnotationTextRange? textRange;
  final String? quote;
  final List<FlutterSelectionRect>? rectangles;
  final FlutterHighlightColor color;
  final String? body;

  const FlutterAnnotation({
    required this.id,
    required this.unit,
    required this.resolution,
    this.textRange,
    this.quote,
    this.rectangles,
    required this.color,
    this.body,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      unit.hashCode ^
      resolution.hashCode ^
      textRange.hashCode ^
      quote.hashCode ^
      rectangles.hashCode ^
      color.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterAnnotation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          unit == other.unit &&
          resolution == other.resolution &&
          textRange == other.textRange &&
          quote == other.quote &&
          rectangles == other.rectangles &&
          color == other.color &&
          body == other.body;
}

enum FlutterAnnotationAssociationOutcome { associated, alreadyAssociated }

class FlutterAnnotationAssociationSource {
  final String versionId;
  final FlutterBookFormat format;
  final String localPath;
  final String fingerprintAlgorithm;
  final int fingerprintVersion;
  final Uint8List fingerprint;
  final BigInt liveAnnotations;

  const FlutterAnnotationAssociationSource({
    required this.versionId,
    required this.format,
    required this.localPath,
    required this.fingerprintAlgorithm,
    required this.fingerprintVersion,
    required this.fingerprint,
    required this.liveAnnotations,
  });

  @override
  int get hashCode =>
      versionId.hashCode ^
      format.hashCode ^
      localPath.hashCode ^
      fingerprintAlgorithm.hashCode ^
      fingerprintVersion.hashCode ^
      fingerprint.hashCode ^
      liveAnnotations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterAnnotationAssociationSource &&
          runtimeType == other.runtimeType &&
          versionId == other.versionId &&
          format == other.format &&
          localPath == other.localPath &&
          fingerprintAlgorithm == other.fingerprintAlgorithm &&
          fingerprintVersion == other.fingerprintVersion &&
          fingerprint == other.fingerprint &&
          liveAnnotations == other.liveAnnotations;
}

class FlutterAnnotationAssociationSourcePage {
  final List<FlutterAnnotationAssociationSource> sources;
  final String? nextCursor;
  final String? previousCursor;

  const FlutterAnnotationAssociationSourcePage({
    required this.sources,
    this.nextCursor,
    this.previousCursor,
  });

  @override
  int get hashCode =>
      sources.hashCode ^ nextCursor.hashCode ^ previousCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterAnnotationAssociationSourcePage &&
          runtimeType == other.runtimeType &&
          sources == other.sources &&
          nextCursor == other.nextCursor &&
          previousCursor == other.previousCursor;
}

enum FlutterAnnotationResolution { exact, recovered, ambiguous, orphaned }

class FlutterAnnotationTextRange {
  final BigInt start;
  final BigInt end;

  const FlutterAnnotationTextRange({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterAnnotationTextRange &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

enum FlutterBookFormat { pdf, epub, cbz }

class FlutterBookmark {
  final PlatformInt64 id;
  final PlatformInt64? bookId;
  final BigInt unit;
  final BigInt? offset;
  final String? title;
  final String? note;
  final String color;
  final String createdAt;

  const FlutterBookmark({
    required this.id,
    this.bookId,
    required this.unit,
    this.offset,
    this.title,
    this.note,
    required this.color,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      unit.hashCode ^
      offset.hashCode ^
      title.hashCode ^
      note.hashCode ^
      color.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBookmark &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          unit == other.unit &&
          offset == other.offset &&
          title == other.title &&
          note == other.note &&
          color == other.color &&
          createdAt == other.createdAt;
}

class FlutterBridgeError implements FrbException {
  final FlutterBridgeErrorKind kind;
  final String message;

  const FlutterBridgeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum FlutterBridgeErrorKind {
  cancelled,
  notFound,
  inaccessible,
  unsupported,
  invalidRequest,
  malformed,
  limitExceeded,
  backendUnavailable,
  renderFailed,
}

class FlutterBufferHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterBufferHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterBufferHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterDocumentHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterDocumentHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDocumentHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterDocumentSummary {
  final FlutterDocumentHandle handle;
  final PlatformInt64? bookId;
  final FlutterBookFormat format;
  final String? title;
  final BigInt logicalUnitCount;

  const FlutterDocumentSummary({
    required this.handle,
    this.bookId,
    required this.format,
    this.title,
    required this.logicalUnitCount,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      bookId.hashCode ^
      format.hashCode ^
      title.hashCode ^
      logicalUnitCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterDocumentSummary &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          bookId == other.bookId &&
          format == other.format &&
          title == other.title &&
          logicalUnitCount == other.logicalUnitCount;
}

enum FlutterHighlightColor { yellow, green, blue, pink, purple }

class FlutterImportItem {
  final String pathKey;
  final FlutterLibraryBook? book;
  final String? error;

  const FlutterImportItem({required this.pathKey, this.book, this.error});

  @override
  int get hashCode => pathKey.hashCode ^ book.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterImportItem &&
          runtimeType == other.runtimeType &&
          pathKey == other.pathKey &&
          book == other.book &&
          error == other.error;
}

class FlutterLibraryBook {
  final PlatformInt64 bookId;
  final String title;
  final String? author;
  final FlutterBookFormat format;
  final String pathKey;
  final bool managed;
  final Uint8List? cover;
  final double progress;
  final String dateAdded;
  final String? lastRead;

  const FlutterLibraryBook({
    required this.bookId,
    required this.title,
    this.author,
    required this.format,
    required this.pathKey,
    required this.managed,
    this.cover,
    required this.progress,
    required this.dateAdded,
    this.lastRead,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      author.hashCode ^
      format.hashCode ^
      pathKey.hashCode ^
      managed.hashCode ^
      cover.hashCode ^
      progress.hashCode ^
      dateAdded.hashCode ^
      lastRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterLibraryBook &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          author == other.author &&
          format == other.format &&
          pathKey == other.pathKey &&
          managed == other.managed &&
          cover == other.cover &&
          progress == other.progress &&
          dateAdded == other.dateAdded &&
          lastRead == other.lastRead;
}

class FlutterLibraryPage {
  final List<FlutterLibraryBook> books;
  final bool hasMore;

  const FlutterLibraryPage({required this.books, required this.hasMore});

  @override
  int get hashCode => books.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterLibraryPage &&
          runtimeType == other.runtimeType &&
          books == other.books &&
          hasMore == other.hasMore;
}

class FlutterOpenRequest {
  final String localId;
  final String pathKey;
  final FlutterBookFormat? formatHint;

  const FlutterOpenRequest({
    required this.localId,
    required this.pathKey,
    this.formatHint,
  });

  @override
  int get hashCode => localId.hashCode ^ pathKey.hashCode ^ formatHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterOpenRequest &&
          runtimeType == other.runtimeType &&
          localId == other.localId &&
          pathKey == other.pathKey &&
          formatHint == other.formatHint;
}

class FlutterReaderSettings {
  final bool continuous;
  final double epubFontSize;
  final double epubLineSpacing;
  final double pdfZoom;

  const FlutterReaderSettings({
    required this.continuous,
    required this.epubFontSize,
    required this.epubLineSpacing,
    required this.pdfZoom,
  });

  @override
  int get hashCode =>
      continuous.hashCode ^
      epubFontSize.hashCode ^
      epubLineSpacing.hashCode ^
      pdfZoom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterReaderSettings &&
          runtimeType == other.runtimeType &&
          continuous == other.continuous &&
          epubFontSize == other.epubFontSize &&
          epubLineSpacing == other.epubLineSpacing &&
          pdfZoom == other.pdfZoom;
}

class FlutterReadingState {
  final BigInt unit;
  final BigInt? offset;
  final double zoom;

  const FlutterReadingState({
    required this.unit,
    this.offset,
    required this.zoom,
  });

  @override
  int get hashCode => unit.hashCode ^ offset.hashCode ^ zoom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterReadingState &&
          runtimeType == other.runtimeType &&
          unit == other.unit &&
          offset == other.offset &&
          zoom == other.zoom;
}

class FlutterRenderedBuffer {
  final FlutterBufferHandle handle;
  final int width;
  final int height;
  final BigInt byteLen;

  const FlutterRenderedBuffer({
    required this.handle,
    required this.width,
    required this.height,
    required this.byteLen,
  });

  @override
  int get hashCode =>
      handle.hashCode ^ width.hashCode ^ height.hashCode ^ byteLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRenderedBuffer &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height &&
          byteLen == other.byteLen;
}

class FlutterSearchMatch {
  final BigInt unit;
  final BigInt offset;
  final BigInt length;
  final String context;

  const FlutterSearchMatch({
    required this.unit,
    required this.offset,
    required this.length,
    required this.context,
  });

  @override
  int get hashCode =>
      unit.hashCode ^ offset.hashCode ^ length.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSearchMatch &&
          runtimeType == other.runtimeType &&
          unit == other.unit &&
          offset == other.offset &&
          length == other.length &&
          context == other.context;
}

class FlutterSelectionCaret {
  final BigInt offset;
  final double x;
  final double alongLine;
  final bool vertical;
  final double top;
  final double bottom;

  const FlutterSelectionCaret({
    required this.offset,
    required this.x,
    required this.alongLine,
    required this.vertical,
    required this.top,
    required this.bottom,
  });

  @override
  int get hashCode =>
      offset.hashCode ^
      x.hashCode ^
      alongLine.hashCode ^
      vertical.hashCode ^
      top.hashCode ^
      bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionCaret &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          x == other.x &&
          alongLine == other.alongLine &&
          vertical == other.vertical &&
          top == other.top &&
          bottom == other.bottom;
}

class FlutterSelectionEndpoint {
  final BigInt offset;
  final BigInt rangeStart;
  final BigInt rangeEnd;
  final FlutterSelectionRect rect;

  const FlutterSelectionEndpoint({
    required this.offset,
    required this.rangeStart,
    required this.rangeEnd,
    required this.rect,
  });

  @override
  int get hashCode =>
      offset.hashCode ^ rangeStart.hashCode ^ rangeEnd.hashCode ^ rect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionEndpoint &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          rangeStart == other.rangeStart &&
          rangeEnd == other.rangeEnd &&
          rect == other.rect;
}

class FlutterSelectionHandle {
  final BigInt registry;
  final BigInt id;

  const FlutterSelectionHandle({required this.registry, required this.id});

  @override
  int get hashCode => registry.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionHandle &&
          runtimeType == other.runtimeType &&
          registry == other.registry &&
          id == other.id;
}

class FlutterSelectionRect {
  final double left;
  final double top;
  final double right;
  final double bottom;

  const FlutterSelectionRect({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ right.hashCode ^ bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionRect &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;
}

class FlutterSelectionSurface {
  final FlutterSelectionHandle handle;
  final double width;
  final double height;
  final String text;
  final bool copyEligible;
  final String? resourcePath;
  final FlutterRenderedBuffer? raster;
  final List<FlutterSelectionEndpoint> endpoints;
  final Uint32List graphemeBoundaries;
  final Uint32List wordBoundaries;
  final List<FlutterSelectionVisualLine> visualLines;

  const FlutterSelectionSurface({
    required this.handle,
    required this.width,
    required this.height,
    required this.text,
    required this.copyEligible,
    this.resourcePath,
    this.raster,
    required this.endpoints,
    required this.graphemeBoundaries,
    required this.wordBoundaries,
    required this.visualLines,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      width.hashCode ^
      height.hashCode ^
      text.hashCode ^
      copyEligible.hashCode ^
      resourcePath.hashCode ^
      raster.hashCode ^
      endpoints.hashCode ^
      graphemeBoundaries.hashCode ^
      wordBoundaries.hashCode ^
      visualLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionSurface &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height &&
          text == other.text &&
          copyEligible == other.copyEligible &&
          resourcePath == other.resourcePath &&
          raster == other.raster &&
          endpoints == other.endpoints &&
          graphemeBoundaries == other.graphemeBoundaries &&
          wordBoundaries == other.wordBoundaries &&
          visualLines == other.visualLines;
}

class FlutterSelectionVisualLine {
  final List<FlutterSelectionCaret> carets;

  const FlutterSelectionVisualLine({required this.carets});

  @override
  int get hashCode => carets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSelectionVisualLine &&
          runtimeType == other.runtimeType &&
          carets == other.carets;
}
